---
# vars file for hostname

_hostname_requirements:
  default:
    - hostname

hostname_requirements: "{{ _hostname_requirements[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | default(_hostname_requirements[ansible_distribution] | default(_hostname_requirements['default'] )) }}"
