---
# tasks file for flask
- name: Create flask directory
  file:
    path: /home/ubuntu/flask
    state: directory
    mode: 0644

- name: Set configuration file and copy to server directly.
  template:
    src: docker-compose.yml.j2
    dest: /home/ubuntu/flask/docker-compose.yml
    mode: 0644
